### ISSUE TITLE
missing function

### ISSUE THREAD

**Issue by baszoetekouw** [S1lentium/IPTools#14]
Great library!  Quite easy to use and works perfectly!
There a a few functions to make life easier that are currently not implemented:
 - instantiate a Range from a Network
 - a contains() method for Network
 - a __toString() method for Range (perhaps by storing its original parse() string)

Any chance you could add these to the library?

**Comment by S1lentium** [comment]
Lately, I have not enough time to work with personal projects. If you want, you can send pull requests with tests, that can be merged with 'v2'-branch.

**Comment by petski** [comment]
> instantiate a Range from a Network

`$network->getHosts()` already returns a Range object. Is that what you need?

> a contains() method for Network

As a work-around you could use `$network->getHosts()->contains(...)`
