### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by imsheng** [S1lentium/IPTools#19]
Iterate over Network IP adresses:

$network = Network::parse('192.168.1.0/24');
foreach($network as $ip) {
	echo (string)$ip . '<br>';
}
192.168.1.0
...
192.168.1.255
Get Network hosts adresses as Range:

$hosts = Network::parse('192.168.1.0/24')->hosts // Range(192.168.1.1, 192.168.1.254);
foreach($hosts as $ip) {
	echo (string)$ip . '<br>';
}
192.168.1.1
...
192.168.1.254

What's the difference?

I need to determine whether IP is in the range

**Comment by S1lentium** [comment]
First is iterating over all possible ips that covers network range;
Second is active host ips that are included in network;
https://en.wikipedia.org/wiki/Host_address
