### ISSUE TITLE
Could you tag a new version

### ISSUE THREAD

**Issue by lyrixx** [S1lentium/IPTools#40]
There are some very useful commit on master that are not release, like the fix for PHP 8.1 e1b7bd3

Thanks

**Comment by Richard-NL** [comment]
Bump, I agree is there and if there is an obstacle to tag it is there anyway we can help?

**Comment by lyrixx** [comment]
gentle ping @S1lentium, may be you missed this notification ❤️

**Comment by S1lentium** [comment]
Tagged as PR
