### ISSUE TITLE
Does your parser to long integer supports IPv6 too?

### ISSUE THREAD

**Issue by nimasdj** [S1lentium/IPTools#5]
Does your parser to long integer supports IPv6 too?
```php
echo IP::parse('some IPv6 here')->long // 
```
is something valid with this class?

**Comment by S1lentium** [comment]
yes, you can parse ipv6 like this:

**Comment by nimasdj** [comment]
Sorry I did not understand. If this is possible then what is missing in current release?

**Comment by S1lentium** [comment]
echo IP::parse('some IPv6 here')->long
