### ISSUE TITLE
New tag for commit 0d9d06 for php 5.3 support

### ISSUE THREAD

**Issue by nrocco** [S1lentium/IPTools#6]
Hi,

First of all I want to thank you for this excellent library.

Would it be possible to `git tag` this commit https://github.com/S1lentium/IPTools/commit/0d9d066265125184b24de20576a661107fde2719 with version number `0.9.0` (or something similar)?

That makes it easier for php 5.3 based projects to depend on this library using composer.

Waiting to hear from you.
Thanks.

**Comment by aindenko** [comment]
:+1:

**Comment by S1lentium** [comment]
Done.

**Comment by nrocco** [comment]
Awesome dude!
